definitions:
  segment.Segment:
    properties:
      id:
        example: "2024-03-09T12:04:08Z"
        type: string
      payload:
        example:
        - 116
        - 104
        - 105
        - 115
        - 32
        - 105
        - 115
        - 32
        - 97
        - 32
        - 98
        - 121
        - 116
        - 101
        - 32
        - 97
        - 114
        - 114
        - 97
        - 121
        - 32
        - 111
        - 102
        - 32
        - 98
        - 121
        - 116
        - 101
        - 115
        items:
          type: integer
        type: array
      segment_number:
        example: 1
        type: integer
      sender_name:
        example: Марк Гревцов
        type: string
      total_segments:
        example: 10
        type: integer
    type: object
  swag.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /channel/code:
    post:
      consumes:
      - application/json
      description: Кодирует и декодирует полученный в виде байт сегмент, вносит ошибку,
        исправляет ее, так же с вероятностью возвращает сегмент на траспортный уровень.
      parameters:
      - description: Пользовательский объект в формате JSON
        in: body
        name: segment
        required: true
        schema:
          $ref: '#/definitions/segment.Segment'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
        "400":
          description: Ошибка в запросе
          schema:
            $ref: '#/definitions/swag.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/swag.ErrorResponse'
      summary: EncodeSegmentSimulate.
      tags:
      - Code
swagger: "2.0"
